object Libs {
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val ktxCore = "androidx.core:core-ktx:${Versions.ktxCore}"
    const val material = "com.google.android.material:material:${Versions.material}"
    const val constraintlayout =
            "androidx.constraintlayout:constraintlayout:${Versions.constraintlayout}"
    const val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlinStdlib}"
    const val testJunit = "junit:junit:${Versions.testJunit}"
    const val circleimageview = "de.hdodenhof:circleimageview:${Versions.circleimageview}"
    const val androidTestJunit = "androidx.test.ext:junit:${Versions.androidTestJunit}"
    const val androidTestespressoCore =
            "androidx.test.espresso:espresso-core:${Versions.androidTestespressoCore}"
    const val gson = "com.google.code.gson:gson:${Versions.gson}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofit_converter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:${Versions.swiperefreshlayout}"
    const val coroutinue = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutine}"
    const val coroutineCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutine}"
    const val liveDataKtx = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.liveDataKtx}"
    const val barrage = "com.kd.easybarrage:library:${Versions.barrage}"
    const val jmessage = "cn.jiguang.sdk:jmessage:${Versions.jmessage}"
    const val jcore = "cn.jiguang.sdk:jcore:${Versions.jcore}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val wheelview = "com.contrarywind:wheelview:${Versions.wheel}"
    const val kawaii = "com.carson_ho:Kawaii_LoadingView:${Versions.kawaii}"
    const val navigationFragment = "androidx.navigation:navigation-fragment:${Versions.navigation}"
    const val navigationUI = "androidx.navigation:navigation-ui:${Versions.navigation}"
    const val cardView = "androidx.cardview:cardview:${Versions.cardView}"
    const val legacy = "androidx.legacy:legacy-support-v4:${Versions.legacy}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val litePal = "org.litepal.guolindev:core:${Versions.litepal}"
    const val viewModleKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle_version}"
}