object Versions {
    const val circleimageview = "2.1.0"
    const val appCompat = "1.2.0"
    const val kotlinStdlib = "1.5.10"
    const val ktxCore = "1.3.2"
    const val material = "1.3.0"
    const val constraintlayout = "2.0.4"
    const val testJunit = "4.13.2"
    const val androidTestJunit = "1.1.2"
    const val androidTestespressoCore = "3.3.0"
    const val swiperefreshlayout = "1.0.0"
    const val retrofit = "2.9.0"
    const val gson = "2.8.7"
    const val coroutine = "1.4.0"
    const val liveDataKtx = "2.3.0-beta01"
    const val barrage = "0.0.1"
    const val jcore = "2.3.0"
    const val glide = "4.11.0"
    const val jmessage ="2.9.2"
    const val wheel = "4.1.0"
    const val  kawaii= "1.0.0"
    const val navigation = "2.3.2"
    const val cardView = "1.0.0"
    const val legacy = "1.0.0"
    const val okhttp = "4.9.0"
    const val litepal = "3.2.2"
}